<a href="https://colab.research.google.com/github/ugenloc/COLABs/blob/master/colab_numpy_4_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY FOR MACHINE LEARNING CRASH COURSE
>This pratice is based on machine learning crash course by Google:
>The pratice is strictly about how numpy is used in Ml crash course


In [ ]:
import matplotlib as plt
import numpy as np
import pandas as pd
%matplotlib inline

arr = np.array([[11,22,44],[6,7,8],[8,9,10],[11,12,13]])
arr[3,1]

12

### To Create A 2 Dimentional Matrix: With specific values...


In [ ]:
three_to_two_dim_mat = np.array([[3,3,4],[4,3,1],[1,2,4]])
three_to_two_dim_mat

array([[3, 3, 4],
       [4, 3, 1],
       [1, 2, 4]])

### Porpulate a 3 dimensional matrix with 2 elements (0)

In [ ]:
zeeros = np.zeros((3,2))
zeeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
array_sequence_number = np.arange(5,12)
array_sequence_number

array([ 5,  6,  7,  8,  9, 10, 11])

### What is the difference between random.randint && random.ramdom && >>> arrange?

>Arange function: returns a specify sequence of number
Random.random: returns a set or matrix of random floating numbers
Random.randint: returns a set or matrix of random numbers within a specified range




In [ ]:
ran_num = np.random.randint(low = 50, high = 100,  size = (6))
ran_num

array([81, 74, 88, 79, 90, 84])

In [ ]:
random_number = np.random.random(9)
random_number

array([0.98717989, 0.45583862, 0.58177143, 0.90482245, 0.13202064,
       0.42982921, 0.48995738, 0.91589235, 0.681521  ])

### GOOGLE MACHINE LEARNING TASK:

>Create a Linear Dataset
       Assign as sequence of interger from 6-20 to a numpy array named label
      
>Asign 15 values to a numpy array named 'Label' 
Such that 
       label = (3)(feature)+4 = 22


In [ ]:
feature = np.arange(6,21)
feature

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
label = np.random.randint(low = 1, high = 50, size = (15))
label

array([ 7, 11,  8,  4, 42, 12, 24, 32,  8, 48, 14, 46, 29, 12, 26])

In [ ]:
label = (3)*(feature)+4
label

array([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64])

In [ ]:
noise1_label = label -2
noise2_label = label +2
noise1_label

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62])

In [ ]:
noise2_label

array([24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66])