# NUMPY FOR MACHINE LEARNING CRASH COURSE
>>This pratice is based on machine learning crash course by Google:
>>The pratice is strictly about how numpy is used in Ml crash course


In [5]:
import matplotlib as plt
import numpy as np
import pandas as pd
%matplotlib inline

arr = np.array([[11,22,44],[6,7,8],[8,9,10],[11,12,13]])
arr[3,1]

12

### To Create A 2 Dimentional Matrix: With specific values...


In [6]:
three_to_two_dim_mat = np.array([[3,3,4],[4,3,1],[1,2,4]])
three_to_two_dim_mat

array([[3, 3, 4],
       [4, 3, 1],
       [1, 2, 4]])

## Porpulate a 3 dimensional matrix with 2 elements (0)

In [7]:
zeeros = np.zeros((3,2))
zeeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
array_sequence_number = np.arange(5,12)
array_sequence_number

array([ 5,  6,  7,  8,  9, 10, 11])

### What is the difference between >>>random.randint && >>>random.ramdom && >>> arrange?

>>Arange function: returns a specify sequence of number

>>Random.random: returns a set or matrix of random floating numbers

>>Random.randint: returns a set or matrix of random numbers within a specified range




In [9]:
ran_num = np.random.randint(low = 50, high = 100,  size = (6))
ran_num

array([86, 60, 69, 90, 73, 95])

In [10]:
random_number = np.random.random(9)
random_number

array([0.34256741, 0.59024953, 0.02994241, 0.31817179, 0.40480488,
       0.93871427, 0.23257619, 0.81951683, 0.53649205])

### GOOGLE MACHINE LEARNING TASK:

>Create a Linear Dataset
       Assign as sequence of interger from 6-20 to a numpy array named label
      
>Asign 15 values to a numpy array named 'Label'

>Such that 
       label = (3)(feature)+4 = 22


In [21]:
feature = np.arange(6,21)
feature

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [2]:
label = np.random.randint(low = 1, high = 50, size = (15))
label

NameError: name 'np' is not defined

In [3]:
label = (3)*(feature)+4
label

NameError: name 'feature' is not defined

In [1]:
noise1_label = label -2
noise2_label = label +2
noise1_label

NameError: name 'label' is not defined

In [26]:
noise2_label

array([24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66])